use crate::{
    aes::{
        FixedKeyAes,
        FIXED_KEY_AES
    },
    delta::Delta,
    sharing::AuthBitShare,
    preprocessing::TensorFpreGen,
    block::Block,
    matrix::{BlockMatrix, MatrixViewRef},
    tensor_ops::{
        gen_populate_seeds_mem_optimized,
        gen_unary_outer_product,
        gen_unary_outer_product_wide,
    },
};
use rand::{CryptoRng, Rng};

/// Output of `AuthTensorGen::prepare_input_labels`, handed off to
/// `AuthTensorEval::install_input_labels` on matching wire indices.
///
/// Per `.planning/LABELS-BUG-CONTEXT.md` "Correct Target Architecture"
/// (BUG-02), input wire labels are an artifact of garbling — generated by
/// the garbler at garble time after the d-opening, not propagated through
/// preprocessing. This struct carries the eval-side halves of the input
/// sharings, the cleartext masked bits required for GGM-tree traversal,
/// and the LSB-shift blocks that align eval's wire-label LSBs with the
/// GGM-tree convention.
#[derive(Clone, Debug)]
pub struct InputLabelsForEval {
    /// Eval's halves of (sharing of x_i under δ_a). Length n.
    /// Each entry is the `key` half of an auth-bit-style sharing of
    /// gen's input bit x_i; gen retains the `mac` half locally in
    /// `AuthTensorGen.x_gen`. Pair encodes `x_i · δ_a`.
    pub x_input_eval_keys: Vec<Block>,
    /// Eval's halves of (sharing of y_j under δ_a). Length m.
    pub y_input_eval_keys: Vec<Block>,
    /// Cleartext masked bits d_x[i] = x_i XOR α_i. Length n.
    /// Used by eval as choice bits for first-half GGM-tree traversal,
    /// replacing the prior LSB-of-wire-label readout.
    pub masked_x_bits: Vec<bool>,
    /// Cleartext masked bits d_y[j] = y_j XOR β_j. Length m.
    /// Used for second-half GGM-tree traversal.
    pub masked_y_bits: Vec<bool>,
    /// LSB-shift blocks for x: `(x_i XOR a_i) · δ_a` per i. Length n.
    /// Eval XORs this into its `masked_x_gen[i]` during install. Without
    /// the shift, eval's wire-label LSB would be `b_i` (eval's local
    /// α-share); with it, the LSB becomes `d_i` — matching the GGM-tree
    /// convention that `gen_populate_seeds_mem_optimized` requires
    /// (gen's seed LSB=0, eval's seed LSB=d). Combined gen+eval sum is
    /// unchanged because gen has already XOR'd the same shift into its
    /// own `masked_x_gen` before this struct is returned.
    pub x_lsb_shifts: Vec<Block>,
    /// LSB-shift blocks for y. Length m. See `x_lsb_shifts`.
    pub y_lsb_shifts: Vec<Block>,
}

pub struct AuthTensorGen {
    cipher: &'static FixedKeyAes,
    chunking_factor: usize,

    n: usize,
    m: usize,

    pub delta_a: Delta,

    /// Underlying auth-bit triples + lowered Block-form sharings; see
    /// `TensorFpreGen` field doc for semantics. The `_eval` and `_gen` Block
    /// fields are local-only lowerings, populated by preprocessing and
    /// consumed by online code without further interaction.
    pub alpha_auth_bit_shares: Vec<AuthBitShare>,
    pub alpha_eval: Vec<Block>,
    pub alpha_gen:  Vec<Block>,
    pub beta_auth_bit_shares: Vec<AuthBitShare>,
    pub beta_eval: Vec<Block>,
    pub beta_gen:  Vec<Block>,
    pub correlated_auth_bit_shares: Vec<AuthBitShare>,
    pub correlated_eval: Vec<Block>,
    pub correlated_gen:  Vec<Block>,
    pub gamma_auth_bit_shares: Vec<AuthBitShare>,
    pub gamma_eval: Vec<Block>,
    pub gamma_gen:  Vec<Block>,

    /// Gen's half of (sharing of x under δ_a). Length n. Populated by
    /// `prepare_input_labels` (BUG-02 / Phase 1.2). Auth-bit-style:
    /// gen retains the `mac` half here; eval receives the `key` half via
    /// `InputLabelsForEval.x_input_eval_keys`. Pair encodes `x_i · δ_a`.
    pub x_gen: Vec<Block>,
    /// Gen's half of (sharing of y under δ_a). Length m.
    pub y_gen: Vec<Block>,
    /// Gen's half of (sharing of x XOR α under δ_a) — the input wire
    /// label, gen side. Length n. Populated by `prepare_input_labels`.
    /// Equals `x_gen[i] XOR (key_g_α XOR a_i · δ_a)`. Used as the
    /// GGM-tree seed input by `garble_first_half` once callers migrate
    /// (Phase 1.2(b)).
    pub masked_x_gen: Vec<Block>,
    /// Gen's half of (sharing of y XOR β under δ_a). Length m.
    pub masked_y_gen: Vec<Block>,

    pub first_half_out: BlockMatrix,
    pub second_half_out: BlockMatrix,

    /// D_ev (rho-half) accumulator for the first half-outer-product. Phase 9 P2-02.
    /// Mirrors `first_half_out` but accumulates the rho-half PRG outputs from
    /// `gen_unary_outer_product_wide`. Written by `garble_first_half_p2` /
    /// `garble_second_half_p2`; consumed by `garble_final_p2`.
    pub first_half_out_ev: BlockMatrix,
    /// D_ev (rho-half) accumulator for the second half-outer-product. Phase 9 P2-02.
    pub second_half_out_ev: BlockMatrix,

    /// Set to `true` by `garble_final()`. `compute_lambda_gamma()` asserts
    /// this flag to prevent silent garbage output when called out of order.
    final_computed: bool,
}

impl AuthTensorGen {
    pub fn new(n: usize, m: usize, chunking_factor: usize) -> Self {
        Self {
            cipher: &(*FIXED_KEY_AES),
            n,
            m,
            chunking_factor,
            delta_a: Delta::random(&mut rand::rng()),
            alpha_auth_bit_shares: Vec::new(),
            alpha_eval: Vec::new(),
            alpha_gen: Vec::new(),
            beta_auth_bit_shares: Vec::new(),
            beta_eval: Vec::new(),
            beta_gen: Vec::new(),
            correlated_auth_bit_shares: Vec::new(),
            correlated_eval: Vec::new(),
            correlated_gen: Vec::new(),
            gamma_auth_bit_shares: Vec::new(),
            gamma_eval: Vec::new(),
            gamma_gen: Vec::new(),
            x_gen: Vec::new(),
            y_gen: Vec::new(),
            masked_x_gen: Vec::new(),
            masked_y_gen: Vec::new(),
            first_half_out: BlockMatrix::new(n, m),
            second_half_out: BlockMatrix::new(m, n),
            first_half_out_ev: BlockMatrix::new(n, m),
            second_half_out_ev: BlockMatrix::new(m, n),
            final_computed: false,
        }
    }

    pub fn new_from_fpre_gen(fpre_gen: TensorFpreGen) -> Self {
        Self {
            cipher: &(*FIXED_KEY_AES),
            n: fpre_gen.n,
            m: fpre_gen.m,
            chunking_factor: fpre_gen.chunking_factor,
            delta_a: fpre_gen.delta_a,
            alpha_auth_bit_shares: fpre_gen.alpha_auth_bit_shares,
            alpha_eval: fpre_gen.alpha_eval,
            alpha_gen: fpre_gen.alpha_gen,
            beta_auth_bit_shares: fpre_gen.beta_auth_bit_shares,
            beta_eval: fpre_gen.beta_eval,
            beta_gen: fpre_gen.beta_gen,
            correlated_auth_bit_shares: fpre_gen.correlated_auth_bit_shares,
            correlated_eval: fpre_gen.correlated_eval,
            correlated_gen: fpre_gen.correlated_gen,
            gamma_auth_bit_shares: fpre_gen.gamma_auth_bit_shares,
            gamma_eval: fpre_gen.gamma_eval,
            gamma_gen: fpre_gen.gamma_gen,
            x_gen: Vec::new(),
            y_gen: Vec::new(),
            masked_x_gen: Vec::new(),
            masked_y_gen: Vec::new(),
            first_half_out: BlockMatrix::new(fpre_gen.n, fpre_gen.m),
            second_half_out: BlockMatrix::new(fpre_gen.m, fpre_gen.n),
            first_half_out_ev: BlockMatrix::new(fpre_gen.n, fpre_gen.m),
            second_half_out_ev: BlockMatrix::new(fpre_gen.m, fpre_gen.n),
            final_computed: false,
        }
    }

    /// Generate input wire labels at garble time and emit the eval-side
    /// halves for hand-off via `AuthTensorEval::install_input_labels`.
    ///
    /// Per `.planning/LABELS-BUG-CONTEXT.md` "Correct Target Architecture"
    /// (BUG-02), input wire labels are NOT a preprocessing artifact —
    /// they are generated by the garbler at garble time after the masked
    /// input bits `d_x = x XOR α`, `d_y = y XOR β` are established by an
    /// interactive opening over the α / β auth-bit shares.
    ///
    /// Construction (paper-faithful, auth-bit-style algebra):
    /// 1. For each input bit x_i, gen runs a `build_share`-style auth-bit
    ///    encoding under δ_a: sample random `input_key` with `lsb = 0`,
    ///    derive `input_mac = input_key XOR x_i · δ_a` (so
    ///    `lsb(input_mac) = x_i`). Gen stores `input_mac` in
    ///    `self.x_gen[i]`; eval receives `input_key` via the returned
    ///    `x_input_eval_keys[i]`. Pair encodes `x_i · δ_a`.
    /// 2. The wire-label sharing of `(x_i XOR α_i)` under δ_a is the
    ///    IT-MAC sum of the input-share and the α-share (after the
    ///    transformation `key_g_α XOR a_i · δ_a` for the gen side,
    ///    computed on-the-fly until the bigger preprocessing-struct
    ///    restructure lands). Gen stores its half in
    ///    `self.masked_x_gen[i]`; eval computes its half inside
    ///    `install_input_labels` as `input_key XOR mac_e_α`.
    /// 3. Cleartext `d_x[i] = x_i XOR a_i XOR b_i` is computed by the
    ///    in-process simulator and returned for placement in
    ///    `AuthTensorEval.masked_x_bits[i]`. Eval uses it as the
    ///    GGM-tree choice bit for first-half traversal.
    ///
    /// Same construction for y / β / second half.
    ///
    /// `eval_alpha_gen` and `eval_beta_gen` are the eval's halves of the
    /// α-under-δ_a and β-under-δ_a sharings respectively — i.e., the
    /// "alpha_gen / beta_gen" fields per the user-defined naming
    /// convention `<value>_<delta_owner>`. These are the in-process
    /// stand-in for the inter-party d-opening protocol step: a real
    /// two-party implementation would replace this with a network
    /// round-trip exchanging the bit values plus MAC checks.
    ///
    /// Currently the parameter type is `&[AuthBitShare]` and we extract
    /// `b_i` via `.bit()`. After the bigger preprocessing-struct
    /// restructure the type becomes `&[Block]` and `b_i` derivation
    /// switches to a delta-aware check (e.g. `.lsb()` against the
    /// delta-encoding convention) since `.bit()` won't exist on the
    /// pure-Block representation. The parameter name `eval_alpha_gen`
    /// already matches the post-restructure shape.
    ///
    /// Side effects on `self`:
    /// - `self.x_gen`, `self.y_gen` populated (lengths n, m).
    /// - `self.masked_x_gen`, `self.masked_y_gen` populated.
    ///
    /// MUST be called before `garble_first_half` / `garble_second_half`.
    ///
    /// # Panics
    /// Panics if `eval_alpha_gen.len()` / `eval_beta_gen.len()` does not
    /// match `self.n` / `self.m`, or if `self.alpha_auth_bit_shares` /
    /// `self.beta_auth_bit_shares` are not populated.
    pub fn prepare_input_labels<R: Rng + CryptoRng>(
        &mut self,
        rng: &mut R,
        x: usize,
        y: usize,
        eval_alpha_gen: &[AuthBitShare],
        eval_beta_gen: &[AuthBitShare],
    ) -> InputLabelsForEval {
        assert_eq!(self.alpha_auth_bit_shares.len(), self.n,
            "self.alpha_auth_bit_shares must be populated; len={} expected={}",
            self.alpha_auth_bit_shares.len(), self.n);
        assert_eq!(self.beta_auth_bit_shares.len(), self.m,
            "self.beta_auth_bit_shares must be populated; len={} expected={}",
            self.beta_auth_bit_shares.len(), self.m);
        assert_eq!(eval_alpha_gen.len(), self.n,
            "eval_alpha_gen.len() ({}) must equal self.n ({})",
            eval_alpha_gen.len(), self.n);
        assert_eq!(eval_beta_gen.len(), self.m,
            "eval_beta_gen.len() ({}) must equal self.m ({})",
            eval_beta_gen.len(), self.m);

        let delta_a_block = *self.delta_a.as_block();

        let mut x_input_eval_keys: Vec<Block> = Vec::with_capacity(self.n);
        let mut masked_x_bits: Vec<bool> = Vec::with_capacity(self.n);
        let mut x_lsb_shifts: Vec<Block> = Vec::with_capacity(self.n);
        self.x_gen = Vec::with_capacity(self.n);
        self.masked_x_gen = Vec::with_capacity(self.n);

        for i in 0..self.n {
            let x_i = ((x >> i) & 1) != 0;
            let a_i = self.alpha_auth_bit_shares[i].bit();
            // Eval's local α-share bit. Today via .bit() on the auth-bit
            // representation; post-restructure this becomes a lsb()/equality
            // derivation on the Block-form share.
            let b_i = eval_alpha_gen[i].bit();

            let mut input_key = Block::random(rng);
            input_key.set_lsb(false);
            let input_mac = if x_i { input_key ^ delta_a_block } else { input_key };

            x_input_eval_keys.push(input_key);
            self.x_gen.push(input_mac);

            // Gen's α-share half under δ_a: key_g_α XOR a_i · δ_a.
            let key_g_alpha = *self.alpha_auth_bit_shares[i].key.as_block();
            let gen_alpha_share_da =
                if a_i { key_g_alpha ^ delta_a_block } else { key_g_alpha };

            // LSB-shift to align with the GGM-tree convention
            // (gen's seed LSB=0, eval's seed LSB=d). Without shift,
            // gen's masked_x_gen LSB = x_i XOR a_i; XOR'ing
            // (x_i XOR a_i) · δ_a flips it to 0. Eval applies the same
            // shift block during install, landing eval's LSB on d_i.
            // Combined sum is preserved because both sides XOR the
            // same block.
            let lsb_shift = if x_i ^ a_i { delta_a_block } else { Block::ZERO };

            self.masked_x_gen.push(input_mac ^ gen_alpha_share_da ^ lsb_shift);

            x_lsb_shifts.push(lsb_shift);
            masked_x_bits.push(x_i ^ a_i ^ b_i);
        }

        let mut y_input_eval_keys: Vec<Block> = Vec::with_capacity(self.m);
        let mut masked_y_bits: Vec<bool> = Vec::with_capacity(self.m);
        let mut y_lsb_shifts: Vec<Block> = Vec::with_capacity(self.m);
        self.y_gen = Vec::with_capacity(self.m);
        self.masked_y_gen = Vec::with_capacity(self.m);

        for j in 0..self.m {
            let y_j = ((y >> j) & 1) != 0;
            let beta_a_j = self.beta_auth_bit_shares[j].bit();
            // Eval's local β-share bit. See note on `b_i` above for the
            // post-restructure derivation.
            let beta_b_j = eval_beta_gen[j].bit();

            let mut input_key = Block::random(rng);
            input_key.set_lsb(false);
            let input_mac = if y_j { input_key ^ delta_a_block } else { input_key };

            y_input_eval_keys.push(input_key);
            self.y_gen.push(input_mac);

            let key_g_beta = *self.beta_auth_bit_shares[j].key.as_block();
            let gen_beta_share_da =
                if beta_a_j { key_g_beta ^ delta_a_block } else { key_g_beta };

            let lsb_shift = if y_j ^ beta_a_j { delta_a_block } else { Block::ZERO };

            self.masked_y_gen.push(input_mac ^ gen_beta_share_da ^ lsb_shift);

            y_lsb_shifts.push(lsb_shift);
            masked_y_bits.push(y_j ^ beta_a_j ^ beta_b_j);
        }

        InputLabelsForEval {
            x_input_eval_keys,
            y_input_eval_keys,
            masked_x_bits,
            masked_y_bits,
            x_lsb_shifts,
            y_lsb_shifts,
        }
    }



    pub(crate) fn gen_chunked_half_outer_product(
        &mut self,
        x: &MatrixViewRef<Block>,
        y: &MatrixViewRef<Block>,
        first_half: bool,
    ) -> (Vec<Vec<(Block, Block)>>, Vec<Vec<Block>>) {
    
        let mut chunk_levels: Vec<Vec<(Block, Block)>> = Vec::new();
        let mut chunk_cts: Vec<Vec<Block>> = Vec::new();
    
        for s in 0..((x.rows() + self.chunking_factor-1)/self.chunking_factor) {
            let slice_size: usize;
            if self.chunking_factor *(s+1) > x.rows() {slice_size = x.rows() % self.chunking_factor;} else {slice_size = self.chunking_factor;}
            let mut slice = BlockMatrix::new(slice_size, 1);
            for i in 0..slice_size {
                slice[i] = x[i + s * self.chunking_factor];
            }

            // Extract fields before closure
            let cipher = self.cipher;
            let delta = self.delta_a;

            let mut out = if first_half {
                self.first_half_out.as_view_mut()
            } else {
                self.second_half_out.as_view_mut()
            };

            out.with_subrows(self.chunking_factor * s, slice_size, |part| {
    
                let (gen_seeds, levels) = gen_populate_seeds_mem_optimized(slice.elements_slice(), cipher, delta);
                let gen_cts = gen_unary_outer_product(&gen_seeds, &y, part, cipher);
    
                chunk_levels.push(levels);
                chunk_cts.push(gen_cts);
            });
        }

        (chunk_levels, chunk_cts)
    }

    /// Wide-leaf variant of `gen_chunked_half_outer_product`. Phase 9 P2-02.
    /// Writes BOTH the D_gb output (`first_half_out` or `second_half_out`) AND the
    /// D_ev output (`first_half_out_ev` or `second_half_out_ev`) in a single pass
    /// over the GGM tree. Returns wide chunk_cts of type `Vec<Vec<(Block, Block)>>`.
    pub(crate) fn gen_chunked_half_outer_product_wide(
        &mut self,
        x: &MatrixViewRef<Block>,
        y_d_gb: &MatrixViewRef<Block>,
        y_d_ev: &MatrixViewRef<Block>,
        first_half: bool,
    ) -> (Vec<Vec<(Block, Block)>>, Vec<Vec<(Block, Block)>>) {
        let mut chunk_levels: Vec<Vec<(Block, Block)>> = Vec::new();
        let mut chunk_cts: Vec<Vec<(Block, Block)>> = Vec::new();

        for s in 0..((x.rows() + self.chunking_factor - 1) / self.chunking_factor) {
            let slice_size: usize = if self.chunking_factor * (s + 1) > x.rows() {
                x.rows() % self.chunking_factor
            } else {
                self.chunking_factor
            };

            let mut slice = BlockMatrix::new(slice_size, 1);
            for i in 0..slice_size {
                slice[i] = x[i + s * self.chunking_factor];
            }

            let cipher = self.cipher;
            let delta = self.delta_a;
            let chunking_factor = self.chunking_factor;

            // Borrow both D_gb and D_ev output halves disjointly. We split the
            // ownership manually to obtain two simultaneous &mut BlockMatrix
            // borrows on different struct fields.
            let (out_gb_full, out_ev_full): (
                &mut BlockMatrix,
                &mut BlockMatrix,
            ) = if first_half {
                (&mut self.first_half_out, &mut self.first_half_out_ev)
            } else {
                (&mut self.second_half_out, &mut self.second_half_out_ev)
            };

            let mut out_gb = out_gb_full.as_view_mut();
            let mut out_ev = out_ev_full.as_view_mut();

            // Nested with_subrows: each call yields a sub-view scoped to this
            // chunk's row range. The two views are over distinct backing storage
            // (different BlockMatrix fields), so the outer-then-inner closure
            // ordering is purely lexical — no aliasing concern.
            out_gb.with_subrows(chunking_factor * s, slice_size, |part_gb| {
                out_ev.with_subrows(chunking_factor * s, slice_size, |part_ev| {
                    let (gen_seeds, levels) = gen_populate_seeds_mem_optimized(
                        slice.elements_slice(),
                        cipher,
                        delta,
                    );
                    let gen_cts_wide = gen_unary_outer_product_wide(
                        &gen_seeds,
                        y_d_gb,
                        y_d_ev,
                        part_gb,
                        part_ev,
                        cipher,
                    );

                    chunk_levels.push(levels);
                    chunk_cts.push(gen_cts_wide);
                });
            });
        }

        (chunk_levels, chunk_cts)
    }

    /// returns: the garbler's x and y inputs to the first tensor half gate.
    ///
    /// Under the auth-bit-style construction (BUG-02 / Phase 1.2):
    /// - `x[i] = masked_x_gen[i]` — gen's half of the wire-label sharing
    ///   `(x XOR α) · δ_a` (= input-mac XOR (key_g_α XOR a · δ_a)).
    /// - `y[i] = y_gen[i]` — gen's half of the input sharing of y under
    ///   δ_a (= input-mac for y). The β-share cancellation is implicit:
    ///   `masked_y_gen XOR (key_g_β XOR a_β · δ_a) = y_gen`.
    ///
    /// MUST be called after `prepare_input_labels` has populated
    /// `masked_x_gen` and `y_gen`.
    pub fn get_first_inputs(&self) -> (BlockMatrix, BlockMatrix) {
        assert_eq!(self.masked_x_gen.len(), self.n,
            "get_first_inputs: masked_x_gen not populated; call prepare_input_labels first");
        assert_eq!(self.y_gen.len(), self.m,
            "get_first_inputs: y_gen not populated; call prepare_input_labels first");

        let mut x = BlockMatrix::new(self.n, 1);
        for i in 0..self.n {
            x[i] = self.masked_x_gen[i];
        }

        let mut y = BlockMatrix::new(self.m, 1);
        for j in 0..self.m {
            y[j] = self.y_gen[j];
        }

        (x, y)
    }

    /// returns: the garbler's x and y inputs to the second tensor half gate.
    ///
    /// Under the auth-bit-style construction:
    /// - `x[i] = masked_y_gen[i]` — gen's half of the wire-label sharing
    ///   `(y XOR β) · δ_a`.
    /// - `y[i]` = gen's half of the α-sharing under δ_a
    ///   (`key_g_α XOR a_α · δ_a`). Same as before — α-sharing handling
    ///   is unchanged in Phase 1.2 since α stays a preprocessing artifact.
    ///
    /// MUST be called after `prepare_input_labels` has populated
    /// `masked_y_gen`.
    pub fn get_second_inputs(&self) -> (BlockMatrix, BlockMatrix) {
        assert_eq!(self.masked_y_gen.len(), self.m,
            "get_second_inputs: masked_y_gen not populated; call prepare_input_labels first");

        let mut x = BlockMatrix::new(self.m, 1);
        for j in 0..self.m {
            x[j] = self.masked_y_gen[j];
        }

        let mut y = BlockMatrix::new(self.n, 1);
        for i in 0..self.n {
            let alpha_share =
                if self.alpha_auth_bit_shares[i].bit()
                {
                    self.delta_a.as_block() ^ self.alpha_auth_bit_shares[i].key.as_block()
                } else {
                    *self.alpha_auth_bit_shares[i].key.as_block()
                };
            y[i] = alpha_share;
        }

        (x, y)
    }

    pub fn garble_first_half(&mut self) -> (Vec<Vec<(Block, Block)>>, Vec<Vec<Block>>) {
        let (x, y) = self.get_first_inputs();
        let (chunk_levels, chunk_cts) = self.gen_chunked_half_outer_product(&x.as_view(), &y.as_view(), true);

        (chunk_levels, chunk_cts)
    }

    pub fn garble_second_half(&mut self) -> (Vec<Vec<(Block, Block)>>, Vec<Vec<Block>>) {
        let (x, y) = self.get_second_inputs();
        let (chunk_levels, chunk_cts) = self.gen_chunked_half_outer_product(&x.as_view(), &y.as_view(), false);

        (chunk_levels, chunk_cts)
    }

    /// Combines both half-outer-product outputs with the correlated preprocessing
    /// share to produce the garbled tensor gate output.
    pub fn garble_final(&mut self) {
        assert!(
            !self.final_computed,
            "garble_final called twice on the same instance — \
             first_half_out would be double-XOR'd; create a new instance per gate"
        );
        for i in 0..self.n {
            for j in 0..self.m {
                let correlated_share = if self.correlated_auth_bit_shares[j * self.n + i].bit() {
                    self.delta_a.as_block() ^ self.correlated_auth_bit_shares[j * self.n + i].key.as_block()
                } else {
                    *self.correlated_auth_bit_shares[j * self.n + i].key.as_block()
                };

                self.first_half_out[(i, j)] ^=
                    self.second_half_out[(j, i)] ^
                    correlated_share;
            }
        }
        self.final_computed = true;
    }

    /// Phase 9 P2-02 — y inputs (D_ev half) for `garble_first_half_p2`.
    ///
    /// The garbler does NOT hold `delta_b`. Per the IT-MAC layout in
    /// `auth_tensor_fpre.rs::gen_auth_bit` (lines 66-86), the garbler's
    /// `beta_eval[i].mac` is built as `a_share.mac = key_a.auth(a, delta_b)
    /// = key_a XOR a*delta_b`, where `key_a` is held by the evaluator. Emitting
    /// `mac.as_block()` directly is the correct public-bit encoding under
    /// `delta_b` for the garbler's contribution — no XOR needed. The eval side
    /// XORs in its key view to recover the IT-MAC pair under `delta_b`.
    fn get_first_inputs_p2_y_d_ev(&self) -> BlockMatrix {
        let mut y_ev = BlockMatrix::new(self.m, 1);
        for i in 0..self.m {
            y_ev[i] = self.beta_eval[i];
        }
        y_ev
    }

    fn get_second_inputs_p2_y_d_ev(&self) -> BlockMatrix {
        let mut y_ev = BlockMatrix::new(self.n, 1);
        for i in 0..self.n {
            y_ev[i] = self.alpha_eval[i];
        }
        y_ev
    }

    /// Phase 9 P2-02. Drives the wide GGM tree expansion for the first
    /// half-outer-product. Returns `(chunk_levels, chunk_cts_wide)` where
    /// `chunk_cts_wide: Vec<Vec<(Block, Block)>>` carries the kappa-half AND
    /// rho-half ciphertexts. Writes BOTH `first_half_out` (D_gb) and
    /// `first_half_out_ev` (D_ev) in a single pass.
    pub fn garble_first_half_p2(&mut self) -> (Vec<Vec<(Block, Block)>>, Vec<Vec<(Block, Block)>>) {
        let (x, y_d_gb) = self.get_first_inputs();
        let y_d_ev = self.get_first_inputs_p2_y_d_ev();
        self.gen_chunked_half_outer_product_wide(
            &x.as_view(),
            &y_d_gb.as_view(),
            &y_d_ev.as_view(),
            true,
        )
    }

    /// Phase 9 P2-02. Drives the wide GGM tree expansion for the second
    /// half-outer-product. Mirrors `garble_first_half_p2` with second-half
    /// inputs.
    pub fn garble_second_half_p2(&mut self) -> (Vec<Vec<(Block, Block)>>, Vec<Vec<(Block, Block)>>) {
        let (x, y_d_gb) = self.get_second_inputs();
        let y_d_ev = self.get_second_inputs_p2_y_d_ev();
        self.gen_chunked_half_outer_product_wide(
            &x.as_view(),
            &y_d_gb.as_view(),
            &y_d_ev.as_view(),
            false,
        )
    }

    /// Phase 9 P2-02. Combines both halves into the final D_gb and D_ev output
    /// shares.
    ///
    /// Returns `(d_gb_out, d_ev_out)`:
    /// - `d_gb_out[j*n + i]` = `[v_gamma D_gb]^gb` for gate (i, j); identical to
    ///   the value `garble_final` writes into `first_half_out[(i, j)]`.
    /// - `d_ev_out[j*n + i]` = `[v_gamma D_ev]^gb` for gate (i, j); the new D_ev
    ///   path.
    ///
    /// CRITICAL — Protocol-2 garbler privacy (CONTEXT.md D-10): this method
    /// NEVER returns a masked wire value (no `bool` / no `Vec<bool>`). The
    /// garbler retains both shares privately. The static return type
    /// `(Vec<Block>, Vec<Block>)` enforces the privacy property at compile
    /// time.
    ///
    /// D_ev encoding rule (garbler side): the garbler does NOT hold `delta_b`,
    /// so its public-bit encoding of `correlated_eval[idx]` is simply
    /// `mac.as_block()` — no `delta_b` XOR. See
    /// `get_first_inputs_p2_y_d_ev` doc for derivation.
    pub fn garble_final_p2(&mut self) -> (Vec<Block>, Vec<Block>) {
        assert!(
            !self.final_computed,
            "garble_final_p2 called twice on the same instance — \
             first_half_out would be double-XOR'd; create a new instance per gate"
        );
        // D_gb path: identical to existing `garble_final`.
        for i in 0..self.n {
            for j in 0..self.m {
                let correlated_share_gb = if self.correlated_auth_bit_shares[j * self.n + i].bit() {
                    self.delta_a.as_block() ^ self.correlated_auth_bit_shares[j * self.n + i].key.as_block()
                } else {
                    *self.correlated_auth_bit_shares[j * self.n + i].key.as_block()
                };
                self.first_half_out[(i, j)] ^=
                    self.second_half_out[(j, i)] ^
                    correlated_share_gb;
            }
        }

        // D_ev path: mirror of D_gb but using `correlated_eval`. The
        // garbler emits `mac.as_block()` directly (no `delta_b` XOR — gb does
        // not hold `delta_b`). The eval-side mirror in `evaluate_final_p2`
        // applies its own `delta_b` to the eval-side `key` view to reconstruct
        // the IT-MAC pair under `delta_b`.
        for i in 0..self.n {
            for j in 0..self.m {
                let correlated_share_ev = self.correlated_eval[j * self.n + i];
                self.first_half_out_ev[(i, j)] ^=
                    self.second_half_out_ev[(j, i)] ^
                    correlated_share_ev;
            }
        }

        // Collect output vecs in column-major order (j*n + i).
        let mut d_gb_out: Vec<Block> = Vec::with_capacity(self.n * self.m);
        let mut d_ev_out: Vec<Block> = Vec::with_capacity(self.n * self.m);
        for j in 0..self.m {
            for i in 0..self.n {
                d_gb_out.push(self.first_half_out[(i, j)]);
                d_ev_out.push(self.first_half_out_ev[(i, j)]);
            }
        }

        self.final_computed = true;
        (d_gb_out, d_ev_out)
    }

    /// Computes the garbler's masked output share `[L_gamma]^gb` per (i,j).
    ///
    /// MUST be called AFTER `garble_final()` — `first_half_out` only holds
    /// `[v_gamma D_gb]^gb` once `garble_final` has XORed in the correlated share.
    /// Calling earlier returns garbage.
    ///
    /// Per CONTEXT.md D-04 (paper 5_online.tex line 132):
    ///   `[L_gamma]^gb[j*n+i] = first_half_out[(i,j)].lsb()
    ///                          XOR gamma_auth_bit_shares[j*n+i].bit()`
    ///
    /// Output is column-major: `vec[j * self.n + i]` corresponds to gate output (i, j).
    ///
    /// Note on D_gb vs D_ev: the paper writes `extbit([l_gamma D_gb])` but the Phase 7
    /// `gamma_auth_bit_shares` field stores D_ev-authenticated shares. This is correct:
    /// `AuthBitShare::bit()` returns `self.value`, which is the per-party local share
    /// of the bit — independent of which delta authenticated the share. See
    /// 08-RESEARCH.md Pitfall 1 for the full justification.
    ///
    /// # Panics
    /// Panics if `gamma_auth_bit_shares.len() != self.n * self.m`. The
    /// `UncompressedPreprocessingBackend` deliberately leaves this vec empty
    /// (Phase 7 stub); use `IdealPreprocessingBackend` for any caller invoking
    /// `compute_lambda_gamma`.
    pub fn compute_lambda_gamma(&self) -> Vec<bool> {
        assert!(
            self.final_computed,
            "compute_lambda_gamma called before garble_final — \
             first_half_out is not yet the combined v_gamma encoding"
        );
        assert_eq!(
            self.gamma_auth_bit_shares.len(),
            self.n * self.m,
            "compute_lambda_gamma requires gamma_auth_bit_shares.len() == n*m; \
             UncompressedPreprocessingBackend leaves this vec empty — \
             use IdealPreprocessingBackend"
        );

        let mut out = Vec::with_capacity(self.n * self.m);
        for j in 0..self.m {
            for i in 0..self.n {
                let v_extbit  = self.first_half_out[(i, j)].lsb();
                let lg_extbit = self.gamma_auth_bit_shares[j * self.n + i].bit();
                out.push(v_extbit ^ lg_extbit);
            }
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::auth_tensor_fpre::TensorFpre;
    use crate::auth_tensor_eval::AuthTensorEval;
    use crate::preprocessing::{IdealPreprocessingBackend, TensorPreprocessing};
    use rand::SeedableRng;
    use rand_chacha::ChaCha12Rng;

    /// Test helper: simulate the d-opening + input-label hand-off so
    /// `gar.garble_*_half` and `ev.evaluate_*_half` can run. Per BUG-02 /
    /// Phase 1.2, input wire labels are no longer populated by
    /// preprocessing — tests must call this between `new_from_fpre_*`
    /// and the first `garble_*` / `evaluate_*` call.
    fn install_test_input_labels(
        gar: &mut AuthTensorGen,
        ev: &mut AuthTensorEval,
        x: usize,
        y: usize,
    ) {
        let mut rng = ChaCha12Rng::seed_from_u64(0xDEAD_BEEF);
        let labels = gar.prepare_input_labels(
            &mut rng, x, y,
            &ev.alpha_auth_bit_shares, &ev.beta_auth_bit_shares,
        );
        ev.install_input_labels(labels);
    }

    #[test]
    fn test_garble_first_half() {
        let n = 4;
        let m = 3;

        let mut fpre = TensorFpre::new(0, n, m, 6);
        fpre.generate_ideal();

        let (fpre_gen, fpre_eval) = fpre.into_gen_eval();

        assert_eq!(fpre_gen.alpha_auth_bit_shares.len(), n);
        assert_eq!(fpre_gen.beta_auth_bit_shares.len(), m);

        assert_eq!(fpre_gen.correlated_auth_bit_shares.len(), n * m);

        let mut gar = AuthTensorGen::new_from_fpre_gen(fpre_gen);
        let mut ev = AuthTensorEval::new_from_fpre_eval(fpre_eval);

        assert_eq!(gar.alpha_auth_bit_shares.len(), n);
        assert_eq!(gar.beta_auth_bit_shares.len(), m);
        assert_eq!(gar.correlated_auth_bit_shares.len(), n * m);

        install_test_input_labels(&mut gar, &mut ev, 0b1101, 0b110);

        assert_eq!(gar.masked_x_gen.len(), n);
        assert_eq!(gar.masked_y_gen.len(), m);

        let (_chunk_levels, _chunk_cts) = gar.garble_first_half();
    }

    #[test]
    fn test_compute_lambda_gamma_dimensions() {
        let n = 4;
        let m = 3;
        let (fpre_gen, fpre_eval) = IdealPreprocessingBackend.run(n, m, 1, 1);
        let mut gar = AuthTensorGen::new_from_fpre_gen(fpre_gen);
        let mut ev = AuthTensorEval::new_from_fpre_eval(fpre_eval);

        assert_eq!(gar.gamma_auth_bit_shares.len(), n * m,
            "gamma_auth_bit_shares must be length n*m after new_from_fpre_gen");

        install_test_input_labels(&mut gar, &mut ev, 0, 0);

        let (gen_chunk_levels_1, gen_chunk_cts_1) = gar.garble_first_half();
        let _ = (gen_chunk_levels_1, gen_chunk_cts_1);
        let (gen_chunk_levels_2, gen_chunk_cts_2) = gar.garble_second_half();
        let _ = (gen_chunk_levels_2, gen_chunk_cts_2);
        gar.garble_final();

        let lambda = gar.compute_lambda_gamma();
        assert_eq!(lambda.len(), n * m,
            "compute_lambda_gamma must return Vec<bool> of length n*m");
    }

    #[test]
    fn test_compute_lambda_gamma_uses_column_major() {
        let n = 4;
        let m = 3;
        let (fpre_gen, fpre_eval) = IdealPreprocessingBackend.run(n, m, 1, 1);
        let mut gar = AuthTensorGen::new_from_fpre_gen(fpre_gen);
        let mut ev = AuthTensorEval::new_from_fpre_eval(fpre_eval);
        install_test_input_labels(&mut gar, &mut ev, 0, 0);
        let _ = gar.garble_first_half();
        let _ = gar.garble_second_half();
        gar.garble_final();
        let lambda = gar.compute_lambda_gamma();

        // Probe one specific (i, j) entry.
        let i = 2;
        let j = 1;
        let idx = j * n + i; // == 6
        let expected = gar.first_half_out[(i, j)].lsb()
                     ^ gar.gamma_auth_bit_shares[idx].bit();
        assert_eq!(lambda[idx], expected,
            "lambda[j*n+i] at (i=2, j=1) does not match D-04 formula");
    }

    #[test]
    fn test_compute_lambda_gamma_full_consistency() {
        let n = 4;
        let m = 3;
        let (fpre_gen, fpre_eval) = IdealPreprocessingBackend.run(n, m, 1, 1);
        let mut gar = AuthTensorGen::new_from_fpre_gen(fpre_gen);
        let mut ev = AuthTensorEval::new_from_fpre_eval(fpre_eval);
        install_test_input_labels(&mut gar, &mut ev, 0, 0);
        let _ = gar.garble_first_half();
        let _ = gar.garble_second_half();
        gar.garble_final();
        let lambda = gar.compute_lambda_gamma();

        for j in 0..m {
            for i in 0..n {
                let idx = j * n + i;
                let expected = gar.first_half_out[(i, j)].lsb()
                             ^ gar.gamma_auth_bit_shares[idx].bit();
                assert_eq!(lambda[idx], expected,
                    "D-04 formula mismatch at (i={}, j={}, idx={})", i, j, idx);
            }
        }
    }

    #[test]
    fn test_garble_final_p2_returns_two_block_vecs_no_lambda() {
        // P2-02: garble_final_p2 return type contains NO masked wire value (no Vec<bool>).
        // Statically the type is (Vec<Block>, Vec<Block>) — there is no bool field.
        let n = 4;
        let m = 3;
        let (fpre_gen, fpre_eval) = IdealPreprocessingBackend.run(n, m, 1, 1);
        let mut gar = AuthTensorGen::new_from_fpre_gen(fpre_gen);
        let mut ev = AuthTensorEval::new_from_fpre_eval(fpre_eval);
        install_test_input_labels(&mut gar, &mut ev, 0, 0);

        let (_cl1, _ct1) = gar.garble_first_half_p2();
        let (_cl2, _ct2) = gar.garble_second_half_p2();
        let (d_gb, d_ev) = gar.garble_final_p2();

        assert_eq!(d_gb.len(), n * m, "D_gb output share has length n*m");
        assert_eq!(d_ev.len(), n * m, "D_ev output share has length n*m");
    }

    #[test]
    fn test_garble_first_half_p2_returns_wide_ciphertexts() {
        // P2-01/P2-02: garble_first_half_p2 returns wide chunk_cts of type Vec<Vec<(Block, Block)>>.
        let n = 4;
        let m = 3;
        let (fpre_gen, fpre_eval) = IdealPreprocessingBackend.run(n, m, 1, 1);
        let mut gar = AuthTensorGen::new_from_fpre_gen(fpre_gen);
        let mut ev = AuthTensorEval::new_from_fpre_eval(fpre_eval);
        install_test_input_labels(&mut gar, &mut ev, 0, 0);

        let (_chunk_levels, chunk_cts) = gar.garble_first_half_p2();
        // Each ciphertext entry is (Block, Block) — verifies wide type at compile time.
        for chunk in &chunk_cts {
            for (kappa, rho) in chunk {
                let _: &Block = kappa;
                let _: &Block = rho;
            }
        }
        assert!(!chunk_cts.is_empty(), "chunk_cts must be non-empty");
    }
}